server {
    listen ${PORT};
    root /usr/share/nginx/html;
    index index.html;
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        add_header Cache-Control "no-cache";
        try_files $uri $uri/ /index.html;
    }
}
